config/routes.rb
Rails.application.routes.draw do
  require 'constraints/short_dispatcher'
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions", invitations: "users/invitations" }
  namespace :admin do
    resources :users
    resources :organizations
    resources :domains, :id => /[^\/]+/, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :mailboxes, :id => /[^\/]+/, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :blog_posts, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :pages, only: [:index, :new, :edit, :create, :update, :destroy]
    get '/' => 'dashboard#index'
  end
  resources :users, only: [:index, :show]
  resources :blog_posts, path: 'blog', only: [:index, :show]
  resources :pages, only: [:index, :show]

  match '/contact', to: 'contact#create', :via => 'post', :as => 'emails'

  match '/:id', to: Constraints::ShortDispatcher.new(self), :via => 'get', :as => 'vanity'
  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  include HumanizeName
  include VanitizeUrl

  attr_accessor :login
  default_scope -> { order('users.created_at DESC') }

  rolify
  extend FriendlyId
  friendly_id :username, use: [:slugged, :finders]
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, :presence => true, :uniqueness => { :case_sensitive => false }
  validates :username, length: 2..15, format: { with: /\A(?:[a-z0-9][_]?)*[a-z0-9]\z/i, message: "invalid."} # "may only contain letters, numbers and underscores, must start and end with a letter or number, and cannot contain more than one underscore in a row."
  validates :username, format: { without: /\A\d+\Z/, message: "cannot contain only numbers." }
  # validates :username, format: { without: /\A(?:admin|about|users|staff|login|signin|signup|register|edit|profile)\Z/i, message: "restricted." }

  has_one :profile, :dependent => :destroy
  accepts_nested_attributes_for :profile, :update_only => true

  has_many :blog_posts, :dependent => :destroy
  has_many :pages, :dependent => :destroy

  has_many :organizations, :dependent => :destroy
  accepts_nested_attributes_for :organizations, :update_only => true, reject_if: proc { |attributes| attributes['name'].blank? }

  has_many :domains, :as => :owner, :dependent => :destroy

  def full_name
    "#{profile.first_name} #{profile.last_name}"
  end

  def name
    full_name
  end

  def should_generate_new_friendly_id?
    slug.blank? || username_changed?
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions.to_hash).first
    end
  end

  private

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @organizations = @user.organizations
    @domains = @user.domains + Domain.where({owner: @organizations})
    @mailboxes = Mailbox.where({ domain: @domains })
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.username.blank?
      @user.username = "u_" + Array.new(8){ [*'0'..'9',*'A'..'Z',*'a'..'z'].sample }.join
    end
    if !@user.email.blank?
      @user.slug = @user.username
      @user.invite!(current_user)
      redirect_to admin_users_path
    else
      @user.errors.add(:email, "cannot be blank.")
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to admin_users_path
    else
      render 'edit'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :profile_attributes => [:first_name, :last_name, :bio])
  end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  before_filter :configure_invite_params, only: [:create]
  before_filter :configure_accept_invitation_params, only: [:update]

  # GET /resource/invitation/new
  # def new
  #   super
  # end

  # POST /resource/invitation
  def create
    self.resource = invite_resource
    resource_invited = resource.errors.empty?

    yield resource if block_given?

    if resource_invited
      if resource.username.blank?
        resource.username = "u_" + Array.new(8){ [*'0'..'9',*'A'..'Z',*'a'..'z'].sample }.join
        resource.save
      end
      if is_flashing_format? && self.resource.invitation_sent_at
        set_flash_message :notice, :send_instructions, :email => self.resource.email
      end
      respond_with resource, :location => after_invite_path_for(current_inviter)
    else
      respond_with_navigational(resource) { render :new }
    end
  end

  # GET /resource/invitation/accept?invitation_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/invitation
  # def update
  #   super
  # end

  # DELETE /resource/invitation/remove?invitation_token=abcdef
  # def destroy
  #   super
  # end

  protected

  # You can put the params you want to permit in the empty array.
  def configure_invite_params
    devise_parameter_sanitizer.for(:invite) << [:email]
  end

  # You can put the params you want to permit in the empty array.
  def configure_accept_invitation_params
    devise_parameter_sanitizer.for(:accept_invitation) << [:email, :username, :profile_attributes => [:first_name, :last_name, :bio], :organizations_attributes => [:name]]
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_sign_up_params, only: [:create]
  before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # You can put the params you want to permit in the empty array.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) << [:email, :username, :profile_attributes => [:first_name, :last_name, :bio], :organizations_attributes => [:name]]
  end

  # You can put the params you want to permit in the empty array.
  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) << [:email, :username, :profile_attributes => [:first_name, :last_name, :bio]]
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # You can put the params you want to permit in the empty array.
  def configure_sign_in_params
    devise_parameter_sanitizer.for(:sign_in) << [:login]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/views/admin/users/_user.html.haml
%tr
  %td
    %a.github{:href => admin_user_path(user.slug), :style => 'display:block;margin:-8px;padding:8px;'}
      - if params[:action] == 'index'
        %strong= user_counter + 1
      - else
        %strong 1
  %td
    %a.github{:href => admin_user_path(user.slug), :style => 'display:block;margin:-8px;padding:8px;'}
      - if user.profile
        = user.full_name
      %small (#{user.username})
  %td
    %a.github{:href => admin_user_path(user.slug), :style => 'display:block;margin:-8px;padding:8px;'}
      = user.email
  %td
    %a.github{:href => admin_user_path(user.slug), :style => 'display:block;margin:-8px;padding:8px;'}
      - if user.profile && !user.profile.bio.blank?
        = truncate(user.profile.bio, length: 30)
      - else
        %i ...
  %td.text-center
    %a.github{:href => admin_user_path(user.slug), :style => 'display:block;margin:-8px;padding:8px;'}
      = user.organizations.count
  %td.text-center
    %a.github{:href => admin_user_path(user.slug), :style => 'display:block;margin:-8px;padding:8px;'}
      = user.domains.count + Domain.where({owner: user.organizations}).all.count
  %td.text-center
    %a.github{:href => admin_user_path(user.slug), :style => 'display:block;margin:-8px;padding:8px;'}
      = Mailbox.where({domain: user.domains}).all.count + Mailbox.where({domain: Organization.where({owner: user}).all}).all.count
  %td
    %a.github{:href => admin_user_path(user.slug), :style => 'display:block;margin:-8px;padding:8px;'}
      - if user.roles.any?
        = user.roles.first.name.capitalize
      - else
        %i ...
  %td
    %a{:href => vanity_path(user.slug)}
      %i.fa.fa-fw.fa-eye.blue
    %a{:href => edit_admin_user_path(user.slug)}
      %i.fa.fa-fw.fa-pencil.olive
    %a{:href => admin_user_path(user.slug), 'data-method' => 'delete', :rel => 'nofollow', 'data-confirm' => 'Are you sure?'}
      %i.fa.fa-fw.fa-trash-o.rubylang

app/views/admin/users/edit.html.haml
.col-xs-12
  .content-panel
    %h2.headline.yellowmountain User
    %div
      = form_for([:admin, @user]) do |f|

        - unless @user.errors.empty?
          .alert.alert-error.alert-danger
            %button.close{'data-dismiss' => 'alert', :type => 'button'} x
            %ul
              - @user.errors.full_messages.each do |e|
                %li= e

        = f.fields_for :profile, @user.profile || @user.build_profile do |ff|
          .form-group
            = ff.label :first_name
            = ff.text_field :first_name, :class => 'form-control'
          .form-group
            = ff.label :last_name
            = ff.text_field :last_name, :class => 'form-control'
          .form-group
            = ff.label :bio
            = ff.text_area :bio, :class => 'form-control'

        .form-group
          = f.label :username
          = f.text_field :username, :class => 'form-control'

        .form-group
          = f.label :email
          = f.text_field :email, :class => 'form-control'

        .actions
          = f.submit "Update", :class => 'btn btn-default'

app/views/admin/users/index.html.haml
.col-xs-12
  .content-panel
    %h2.yellowmountain.headline Users
    .table-responsive
      %table.table.table-hover
        %thead
          %tr
            %th #
            %th Name
            %th Email
            %th Bio
            %th.text-center
              %i.fa.fa-briefcase
            %th.text-center
              %i.fa.fa-server
            %th.text-center
              %i.fa.fa-envelope
            %th Roles
            %th
        %tbody.bg-white
          = render @users

app/views/admin/users/new.html.haml
.col-xs-12
  .content-panel
    %h2.headline.yellowmountain User
    %div
      = form_for([:admin, @user]) do |f|

        - unless @user.errors.empty?
          .alert.alert-error.alert-danger
            %button.close{'data-dismiss' => 'alert', :type => 'button'} x
            %ul
              - @user.errors.full_messages.each do |e|
                %li= e

        = f.fields_for :profile, @user.profile || @user.build_profile do |ff|
          .form-group
            = ff.label :first_name
            = ff.text_field :first_name, :class => 'form-control'
          .form-group
            = ff.label :last_name
            = ff.text_field :last_name, :class => 'form-control'
          .form-group
            = ff.label :bio
            = ff.text_area :bio, :class => 'form-control'

        .form-group
          = f.label :username
          = f.text_field :username, :class => 'form-control'

        .form-group
          = f.label :email
          = f.email_field :email, :class => 'form-control'

        .actions
          = f.submit "Save", :class => 'btn btn-default'

app/views/admin/users/show.html.haml
.col-xs-12
  .content-panel.bg-white
    %h2.yellowmountain.headline= @user.full_name
    /%h3.yellowmountain.headline= t('organization').pluralize
    %h3.yellowmountain.headline= Organization.model_name.human.pluralize
    .table-responsive
      %table.table.table-hover
        %thead
          %tr
            %th #
            %th Name
            %th.text-center
              %i.fa.fa-users
            %th.text-center
              %i.fa.fa-server
            %th.text-center
              %i.fa.fa-envelope
            %th
        %tbody.bg-white
          = render @organizations
    .actions
      %a.btn.btn-primary{:href => new_admin_organization_path, :role => 'button'} New #{Organization.model_name.human}
.col-xs-6
  .content-panel.bg-white
    %h3.yellowmountain.headline Domains
    .table-responsive
      %table.table.table-hover
        %thead
          %tr
            %th #
            %th Name
            %th Owner
            %th.text-center
              %i.fa.fa-envelope
            %th
        %tbody.bg-white
          = render @domains
    .actions
      %a.btn.btn-primary{:href => new_admin_domain_path, :role => 'button'} New Domain
  .content-panel.bg-white
    %h3.yellowmountain.headline Other
    .table-responsive
      %table.table.table-hover
        %thead
        %tbody.bg-white
.col-xs-6
  .content-panel.bg-white
    %h3.yellowmountain.headline Mailboxes
    .table-responsive
      %table.table.table-hover
        %thead
          %tr
            %th #
            %th Username
            %th Owner
            %th
        %tbody.bg-white
          = render @mailboxes
    .actions
      %a.btn.btn-primary{:href => new_admin_mailbox_path, :role => 'button'} New Mailbox